name 'cprice404-grafanadash'
version '0.0.6'
source 'git clone https://github.com/cprice404/puppet-grafanadash'
author 'Chris Price'
license 'Mozilla Public License Version 2.0'
summary 'Grafana Dashboard module'
description 'Installs graphite and grafana'
project_page 'https://github.com/cprice404/puppet-grafanadash'

dependency   'dwerder/graphite', '5.16.1'
dependency   'gini/archive', '0.2.0'
dependency   'stahnma/epel', '0.0.6'
dependency   'elasticsearch/elasticsearch', '0.3.2'
